<a href="https://colab.research.google.com/github/Natalie-Bojorquez/CIS3920Group4/blob/main/CIS3920_Group4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [3920] Career Change Prediction
Data file:
* https://raw.githubusercontent.com/vjavaly/Baruch-CIS-3920/refs/heads/main/data/career_change_prediction_100K.csv

In [1]:
from datetime import datetime
print(f'Run time: {datetime.now().strftime("%D %T")}')

Run time: 10/27/26 21:39:45

In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt     # same as 'import matplotlib.pyplot as plt'
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

### Review Raw File & Load Data into Pandas

In [3]:
# Read data file into a Pandas DataFrame
# CSV file format
# Field separator is ','
raw_df = pd.read_csv('https://raw.githubusercontent.com/vjavaly/Baruch-CIS-3920/refs/heads/main/data/career_change_prediction_100K.csv',
                 sep=',')

# 1) Data Sampling

In [4]:
# Display DataFrame dimensions
raw_df.shape  # 100,000 data instances (n rows), 25 features (m columns)

(100000, 25)

In [5]:
# Display DataFrame info: entries, columns, non-null counts, data types
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Employee ID                    100000 non-null  int64
 1   Employer ID                    100000 non-null  int64
 2   Field of Study                 100000 non-null  object
 3   Current Occupation             100000 non-null  object
 4   Age                            99965 non-null   float64
 5   Gender                         99791 non-null   object
 6   Years of Experience            99514 non-null   float64
 7   Education Level                99696 non-null   object
 8   Industry Growth Rate           99401 non-null   object
 9   Job Satisfaction Level         99528 non-null   object
 10  Work-Life Balance              99603 non-null   object
 11  # Job Opportunities            99610 non-null   float64
 12  Salary                         99653 non-null   float64
 13  Job Security Level             100000 non-null  object
 14  Interested in Career Change    100000 non-null  object
 15  Skills Gap                     100000 non-null  object
 16  Family Influence Level         74640 non-null   object
 17  Has Mentor                     99265 non-null   object
 18  Has Certification              99367 non-null   object
 19  Has Freelancing Experience     100000 non-null  object
 20  Willing to Relocate            100000 non-null  object
 21  Professional Network Strength  100000 non-null  object
 22  # Career Change Events         100000 non-null  int64
 23  Technical Proficiency Level    100000 non-null  object
 24  Likely to Change Occupation    100000 non-null  object
dtypes: float64(4), int64(3), object(18)
memory usage: 19.1+ MB

In [6]:
# Separate numeric and categorical variables
numeric_df = raw_df.select_dtypes(include=[np.number])
object_df = raw_df.select_dtypes(exclude=[np.number])

# Inspect categorical variables and their possible values
for col in object_df.columns:
  print(f'{col}: {object_df[col].unique()}', end = '\n''\n')

Field of Study: ['Biology' 'Economics' 'Medicine' 'Computer Science' 'Psychology'
 'Business' 'Education' 'Law' 'Mechanical Engineering' 'Arts']

Current Occupation: ['Economist' 'Doctor' 'Psychologist' 'Lawyer' 'Biologist' 'Teacher'
 'Artist' 'Business Analyst' 'Software Developer' 'Mechanical Engineer']

Gender: ['Female' 'Male' nan]

Education Level: ["Bachelor's" "Master's" 'PhD' 'High School' nan]

Industry Growth Rate: ['Medium' 'High' 'Low' nan]

Job Satisfaction Level: ['Low' 'Moderate' 'High' nan]

Work-Life Balance: ['Excellent' 'Moderate' 'Poor' 'Good' nan]

Job Security Level: ['Excellent' 'Moderate' 'Poor']

Interested in Career Change: ['No' 'Yes']

Skills Gap: ['High' 'Low' 'Moderate']

Family Influence Level: ['High' 'Low' nan 'Medium']

Has Mentor: ['N' 'Y' nan]

Has Certification: ['N' 'Y' nan]

Has Freelancing Experience: ['N' 'Y']

Willing to Relocate: ['No' 'Yes']

Professional Network Strength: ['Strong' 'Weak' 'Average']

Technical Proficiency Level: ['Intermediate' 'Beginner' 'Expert']

Likely to Change Occupation: ['Likely' 'Unlikely']

In [7]:
# Display summary statistics of numeric columns
raw_df.describe()

,Employee ID,Employer ID,Age,Years of Experience,# Job Opportunities,Salary,# Career Change Events
count,100000.000000,100000.000000,99965.000000,99514.000000,99610.000000,99653.000000,100000.000000
mean,499818.735850,53540.588850,39.602661,19.486324,50.283656,109003.983563,1.008990
std,231006.203232,24529.058757,11.623643,11.517150,28.874685,51212.416007,0.814688
min,100008.000000,13309.000000,20.000000,0.000000,1.000000,30005.000000,0.000000
25%,299737.750000,38672.000000,30.000000,10.000000,25.000000,61724.000000,0.000000
50%,499347.000000,53209.000000,40.000000,20.000000,50.000000,107684.000000,1.000000
75%,699583.750000,75617.000000,50.000000,29.000000,75.000000,153334.000000,2.000000
max,899992.000000,92445.000000,59.000000,39.000000,100.000000,199996.000000,2.000000

In [8]:
# Preview first 5 rows
raw_df.head()

,Employee ID,Employer ID,Field of Study,Current Occupation,Age,Gender,Years of Experience,Education Level,Industry Growth Rate,Job Satisfaction Level,...,Skills Gap,Family Influence Level,Has Mentor,Has Certification,Has Freelancing Experience,Willing to Relocate,Professional Network Strength,# Career Change Events,Technical Proficiency Level,Likely to Change Occupation
0,574511,38672,Biology,Economist,38.0,Female,7.0,Bachelor's,Medium,Low,...,High,High,N,N,N,No,Strong,1,Intermediate,Likely
1,447956,22363,Economics,Doctor,44.0,Female,0.0,Master's,Medium,Moderate,...,Low,Low,N,Y,N,No,Weak,1,Beginner,Likely
2,757898,42741,Medicine,Doctor,59.0,Male,10.0,PhD,Medium,Low,...,Low,NaN,N,Y,N,No,Average,2,Beginner,Likely
3,583528,92445,Medicine,Psychologist,57.0,Female,14.0,High School,Medium,Low,...,Moderate,Medium,N,N,N,No,Average,1,Expert,Likely
4,466234,39433,Computer Science,Lawyer,36.0,Female,23.0,PhD,High,Low,...,High,Low,N,N,N,Yes,Weak,0,Intermediate,Likely

In [9]:
# Preview last 5 rows
raw_df.tail()

,Employee ID,Employer ID,Field of Study,Current Occupation,Age,Gender,Years of Experience,Education Level,Industry Growth Rate,Job Satisfaction Level,...,Skills Gap,Family Influence Level,Has Mentor,Has Certification,Has Freelancing Experience,Willing to Relocate,Professional Network Strength,# Career Change Events,Technical Proficiency Level,Likely to Change Occupation
99995,168430,22363,Business,Business Analyst,20.0,Male,4.0,Bachelor's,Low,Low,...,High,Medium,Y,N,N,No,Average,0,Expert,Likely
99996,756046,92445,Psychology,Biologist,58.0,Male,9.0,PhD,Low,Low,...,Moderate,NaN,N,Y,N,Yes,Average,0,Intermediate,Likely
99997,624433,22363,Education,Biologist,27.0,Male,27.0,High School,Medium,Moderate,...,Low,Medium,N,N,N,No,Weak,1,Intermediate,Likely
99998,763689,18718,Business,Mechanical Engineer,23.0,Male,31.0,Bachelor's,Medium,High,...,High,NaN,Y,Y,Y,No,Weak,1,Intermediate,Unlikely
99999,506739,53209,Education,Psychologist,30.0,Male,34.0,PhD,Medium,High,...,Moderate,Medium,NaN,N,N,Yes,Average,0,Expert,Likely

In [10]:
# Display random sample of N rows
raw_df.sample(5)

,Employee ID,Employer ID,Field of Study,Current Occupation,Age,Gender,Years of Experience,Education Level,Industry Growth Rate,Job Satisfaction Level,...,Skills Gap,Family Influence Level,Has Mentor,Has Certification,Has Freelancing Experience,Willing to Relocate,Professional Network Strength,# Career Change Events,Technical Proficiency Level,Likely to Change Occupation
80658,199420,13309,Psychology,Biologist,24.0,Female,14.0,PhD,Low,Low,...,Low,Medium,N,Y,N,No,Weak,2,Intermediate,Likely
35499,166162,64190,Psychology,Mechanical Engineer,52.0,Female,29.0,Master's,High,Low,...,Low,Medium,N,Y,N,No,Weak,1,Beginner,Likely
46964,399771,60225,Law,Lawyer,58.0,Male,19.0,Bachelor's,Low,Moderate,...,High,NaN,N,N,N,Yes,Weak,0,Expert,Likely
60968,667109,55281,Economics,Biologist,51.0,Male,36.0,Master's,Medium,Moderate,...,Low,NaN,Y,N,N,No,Average,1,Beginner,Likely
63109,366270,53209,Psychology,Teacher,51.0,Male,31.0,PhD,Low,Moderate,...,High,NaN,N,N,N,No,Average,2,Beginner,Likely

In [11]:
# Count missing values in each column
total_null = raw_df.isnull().sum()
print(total_null)

Employee ID                          0
Employer ID                          0
Field of Study                       0
Current Occupation                   0
Age                                 35
Gender                             209
Years of Experience                486
Education Level                    304
Industry Growth Rate               599
Job Satisfaction Level             472
Work-Life Balance                  397
# Job Opportunities                390
Salary                             347
Job Security Level                   0
Interested in Career Change          0
Skills Gap                           0
Family Influence Level           25360
Has Mentor                         735
Has Certification                  633
Has Freelancing Experience           0
Willing to Relocate                  0
Professional Network Strength        0
# Career Change Events               0
Technical Proficiency Level          0
Likely to Change Occupation          0
dtype: int64

In [12]:
# Check for duplicate rows across all columns
total_duplicates = raw_df.duplicated().sum()
print(f'Dataset contains {total_duplicates} duplicate rows')

Dataset contains 253 duplicate rows

# Visualization Tools

In [13]:
# Bar Chart

In [14]:
# Correlation Matrix

In [15]:
# Scatter Plot

In [16]:
#Box Plot

# 2) Data Removal

In [17]:
# Create a second DataFrame for data preparation
df = raw_df.copy()

In [18]:
# Remove duplicate rows
df.drop_duplicates(inplace=True)

In [19]:
# Confirm no duplicate rows remain
total_duplicates = df.duplicated().sum()
print(f'Dataset contains {total_duplicates} duplicate rows')

Dataset contains 0 duplicate rows

In [20]:
# Display updated DataFrame dimensions
df.shape  # 99,747 data instances (n), 25 features (m)

(99747, 25)

In [21]:
# Check if Employee ID is unique for every observation
df.shape[0] == df['Employee ID'].nunique()

True

In [22]:
# Set Employee ID as the index to uniquely identify each observation
df.set_index('Employee ID', inplace=True)

# Randomly inspect 5 observations
df.sample(5)

,Employer ID,Field of Study,Current Occupation,Age,Gender,Years of Experience,Education Level,Industry Growth Rate,Job Satisfaction Level,Work-Life Balance,...,Skills Gap,Family Influence Level,Has Mentor,Has Certification,Has Freelancing Experience,Willing to Relocate,Professional Network Strength,# Career Change Events,Technical Proficiency Level,Likely to Change Occupation
Employee ID,,,,,,,,,,,,,,,,,,,,,
287017,75617,Law,Lawyer,38.0,Male,9.0,Bachelor's,High,Low,Moderate,...,Moderate,Medium,N,Y,Y,Yes,Average,1,Beginner,Likely
876463,92445,Psychology,Biologist,22.0,Female,22.0,Bachelor's,Low,Low,Moderate,...,Low,Medium,Y,N,N,Yes,Average,2,Beginner,Likely
712550,92445,Law,Economist,50.0,Female,35.0,High School,Medium,Low,Moderate,...,Low,High,N,Y,N,No,Weak,1,Intermediate,Likely
111443,87326,Medicine,Teacher,24.0,Female,10.0,High School,High,Low,Moderate,...,Moderate,NaN,N,Y,N,No,Average,2,Expert,Likely
437755,18718,Economics,Lawyer,44.0,Male,26.0,High School,Medium,Low,Moderate,...,Moderate,Medium,N,N,Y,No,Strong,0,Intermediate,Likely

In [23]:
# Check for missing values
total_null = df.isnull().sum()
print(total_null)

Employer ID                          0
Field of Study                       0
Current Occupation                   0
Age                                 34
Gender                             205
Years of Experience                484
Education Level                    303
Industry Growth Rate               598
Job Satisfaction Level             471
Work-Life Balance                  397
# Job Opportunities                390
Salary                             345
Job Security Level                   0
Interested in Career Change          0
Skills Gap                           0
Family Influence Level           25293
Has Mentor                         730
Has Certification                  633
Has Freelancing Experience           0
Willing to Relocate                  0
Professional Network Strength        0
# Career Change Events               0
Technical Proficiency Level          0
Likely to Change Occupation          0
dtype: int64

In [24]:
# Examine the distribution of observations across employers
df['Employer ID'].value_counts()  # balanced distribution across 15 employers

Employer ID
50154    6765
18718    6756
38672    6743
60225    6716
13309    6712
55281    6685
75617    6678
64190    6668
87326    6606
42741    6585
92445    6581
53209    6577
39433    6566
90827    6561
22363    6548
Name: count, dtype: int64

In [25]:
# Evaluate whether Employer ID is useful for predicting occupation change
pd.crosstab(
    df['Employer ID'],
    df['Likely to Change Occupation'],
    normalize='index'
    )*100             # Ocupation-change rates are relatively consistent across employers, suggesting limited predictive value

Likely to Change Occupation     Likely  Unlikely
Employer ID
13309                        91.448153  8.551847
18718                        91.548253  8.451747
22363                        92.135003  7.864997
38672                        92.377280  7.622720
39433                        92.126104  7.873896
42741                        91.723614  8.276386
50154                        91.589061  8.410939
53209                        91.698343  8.301657
55281                        91.697831  8.302169
60225                        92.227516  7.772484
64190                        91.481704  8.518296
75617                        91.659179  8.340821
87326                        91.492583  8.507417
90827                        91.678098  8.321902
92445                        91.718584  8.281416

In [26]:
# Drop Employer ID from DataFrame
df.drop(columns='Employer ID', inplace=True)

In [27]:
# Display DataFrame info: entries, columns, non-null counts, data types
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99747 entries, 574511 to 506739
Data columns (total 23 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Field of Study                 99747 non-null  object
 1   Current Occupation             99747 non-null  object
 2   Age                            99713 non-null  float64
 3   Gender                         99542 non-null  object
 4   Years of Experience            99263 non-null  float64
 5   Education Level                99444 non-null  object
 6   Industry Growth Rate           99149 non-null  object
 7   Job Satisfaction Level         99276 non-null  object
 8   Work-Life Balance              99350 non-null  object
 9   # Job Opportunities            99357 non-null  float64
 10  Salary                         99402 non-null  float64
 11  Job Security Level             99747 non-null  object
 12  Interested in Career Change    99747 non-null  object
 13  Skills Gap                     99747 non-null  object
 14  Family Influence Level         74454 non-null  object
 15  Has Mentor                     99017 non-null  object
 16  Has Certification              99114 non-null  object
 17  Has Freelancing Experience     99747 non-null  object
 18  Willing to Relocate            99747 non-null  object
 19  Professional Network Strength  99747 non-null  object
 20  # Career Change Events         99747 non-null  int64
 21  Technical Proficiency Level    99747 non-null  object
 22  Likely to Change Occupation    99747 non-null  object
dtypes: float64(4), int64(1), object(18)
memory usage: 18.3+ MB

In [28]:
# Generate summary statistics for numeric columns in transposed format
df.describe().T      # .T -> rotates the data 90 degrees

,count,mean,std,min,25%,50%,75%,max
Age,99713.0,39.602399,11.623597,20.0,30.0,40.0,50.00,59.0
Years of Experience,99263.0,19.485548,11.517518,0.0,10.0,20.0,29.00,39.0
# Job Opportunities,99357.0,50.287005,28.874180,1.0,25.0,50.0,75.00,100.0
Salary,99402.0,109017.152753,51212.112865,30005.0,61744.0,107696.0,153383.25,199996.0
# Career Change Events,99747.0,1.008923,0.814793,0.0,0.0,1.0,2.00,2.0



# 3) Handling Missing Values

(Natalie's work:)

In [29]:
# Replace missing numeric values with an arithmetic (mean or median) strategy
#  Could also have used strategy='median'
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
df['Age'] = imp_mean.fit_transform(df[['Age']])
df['Years of Experience'] = imp_mean.fit_transform(df[['Years of Experience']])
df['Salary'] = imp_mean.fit_transform(df[['Salary']])
df['# Job Opportunities'] = imp_mean.fit_transform(df[['# Job Opportunities']])

In [30]:
df['Age'].unique()

array([38.        , 44.        , 59.        , 57.        , 36.        ,
       43.        , 34.        , 20.        , 51.        , 55.        ,
       39.        , 45.        , 42.        , 21.        , 49.        ,
       32.        , 48.        , 23.        , 53.        , 47.        ,
       58.        , 56.        , 35.        , 25.        , 37.        ,
       27.        , 30.        , 31.        , 50.        , 54.        ,
       52.        , 46.        , 41.        , 24.        , 33.        ,
       40.        , 29.        , 26.        , 22.        , 28.        ,
       39.60239888])

In [31]:
# Replace missing non-numeric values with a most_frequent (mode) strategy
imp_most_freq = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
df['Gender'] = imp_most_freq.fit_transform(df[['Gender']]).ravel()
df['Education Level'] = imp_most_freq.fit_transform(df[['Education Level']]).ravel()
df['Job Satisfaction Level'] = imp_most_freq.fit_transform(df[['Job Satisfaction Level']]).ravel()
df['Has Mentor'] = imp_most_freq.fit_transform(df[['Has Mentor']]).ravel()
df['Has Certification'] = imp_most_freq.fit_transform(df[['Has Certification']]).ravel()
df['Industry Growth Rate'] = imp_most_freq.fit_transform(df[['Industry Growth Rate']]).ravel()
df['Work-Life Balance'] = imp_most_freq.fit_transform(df[['Work-Life Balance']]).ravel()

In [32]:
#Check again if there are any missing values
df.isnull().any()

Field of Study                   False
Current Occupation               False
Age                              False
Gender                           False
Years of Experience              False
Education Level                  False
Industry Growth Rate             False
Job Satisfaction Level           False
Work-Life Balance                False
# Job Opportunities              False
Salary                           False
Job Security Level               False
Interested in Career Change      False
Skills Gap                       False
Family Influence Level            True
Has Mentor                       False
Has Certification                False
Has Freelancing Experience       False
Willing to Relocate              False
Professional Network Strength    False
# Career Change Events           False
Technical Proficiency Level      False
Likely to Change Occupation      False
dtype: bool

In [33]:
#Drop Family Influence. Compared to other missing values, does not have a lot.
pd.set_option('display.max_columns', None)
df = df.drop('Family Influence Level', axis =1)
df.sample()

,Field of Study,Current Occupation,Age,Gender,Years of Experience,Education Level,Industry Growth Rate,Job Satisfaction Level,Work-Life Balance,# Job Opportunities,Salary,Job Security Level,Interested in Career Change,Skills Gap,Has Mentor,Has Certification,Has Freelancing Experience,Willing to Relocate,Professional Network Strength,# Career Change Events,Technical Proficiency Level,Likely to Change Occupation
Employee ID,,,,,,,,,,,,,,,,,,,,,,
112464,Biology,Psychologist,46.0,Male,20.0,Master's,Medium,Low,Moderate,81.0,141638.0,Moderate,No,Moderate,N,Y,N,No,Strong,2,Beginner,Likely

In [34]:
#Eliminating Index
df = df.reset_index(drop=True)
pd.set_option('display.max_columns', None)
df.sample(5)

,Field of Study,Current Occupation,Age,Gender,Years of Experience,Education Level,Industry Growth Rate,Job Satisfaction Level,Work-Life Balance,# Job Opportunities,Salary,Job Security Level,Interested in Career Change,Skills Gap,Has Mentor,Has Certification,Has Freelancing Experience,Willing to Relocate,Professional Network Strength,# Career Change Events,Technical Proficiency Level,Likely to Change Occupation
4629,Business,Artist,41.0,Male,7.0,Bachelor's,High,Low,Moderate,56.0,111084.0,Moderate,No,Low,Y,N,N,No,Average,0,Expert,Likely
39279,Psychology,Business Analyst,41.0,Male,9.0,PhD,Medium,Low,Poor,98.0,161844.0,Poor,Yes,Low,N,N,N,No,Average,2,Expert,Likely
38564,Business,Teacher,22.0,Male,22.0,PhD,Low,Moderate,Good,8.0,155542.0,Moderate,No,Low,N,Y,N,No,Strong,2,Beginner,Likely
82973,Economics,Lawyer,38.0,Male,22.0,High School,High,Low,Poor,5.0,153894.0,Excellent,No,Low,N,N,N,Yes,Weak,2,Beginner,Likely
82701,Law,Lawyer,20.0,Female,23.0,Master's,Medium,High,Excellent,29.0,31067.0,Excellent,Yes,Low,Y,N,Y,Yes,Strong,1,Beginner,Likely

# 4) Variable Encoding
Ordinal

In [35]:
df['Education Level'].unique()

array(["Bachelor's", "Master's", 'PhD', 'High School'], dtype=object)

In [36]:
 # Ordinal encode Education Level column

# Arrange values according to relative value
CATEGORIES = [['High School', "Bachelor's", "Master's",'PhD']]

# Initialize the OrdinalEncoder
oe = OrdinalEncoder(categories=CATEGORIES)

# Generate encodings
df['Education Level'] = oe.fit_transform(df[['Education Level']])

In [38]:
df['Industry Growth Rate'].unique()

 # Ordinal encode Industry Growth Rate column

# Arrange values according to relative value
CATEGORIES = [['Low', 'Medium', 'High']]

# Initialize the OrdinalEncoder
oe = OrdinalEncoder(categories=CATEGORIES)

# Generate encodings
df['Industry Growth Rate'] = oe.fit_transform(df[['Industry Growth Rate']])

In [40]:
df['Job Satisfaction Level'].unique()

array(['Low', 'Moderate', 'High'], dtype=object)

In [41]:
# Arrange values according to relative value
CATEGORIES = [['Low', 'Moderate', 'High']]

# Initialize the OrdinalEncoder
oe = OrdinalEncoder(categories=CATEGORIES)

# Generate encodings
df['Job Satisfaction Level'] = oe.fit_transform(df[['Job Satisfaction Level']])

In [42]:
df['Work-Life Balance'].unique()

array(['Excellent', 'Moderate', 'Poor', 'Good'], dtype=object)

In [43]:
# Arrange values according to relative value
CATEGORIES = [['Poor', 'Good', 'Moderate', 'Excellent']]

# Initialize the OrdinalEncoder
oe = OrdinalEncoder(categories=CATEGORIES)

# Generate encodings
df['Work-Life Balance'] = oe.fit_transform(df[['Work-Life Balance']])

In [44]:
df['Job Security Level'].unique()

array(['Excellent', 'Moderate', 'Poor'], dtype=object)

In [45]:
# Arrange values according to relative value
CATEGORIES = [['Poor', 'Moderate', 'Excellent']]

# Initialize the OrdinalEncoder
oe = OrdinalEncoder(categories=CATEGORIES)

# Generate encodings
df['Job Security Level'] = oe.fit_transform(df[['Job Security Level']])

In [46]:
df['Skills Gap'].unique()

array(['High', 'Low', 'Moderate'], dtype=object)

In [47]:
# Arrange values according to relative value
CATEGORIES = [['Low', 'Moderate', 'High']]

# Initialize the OrdinalEncoder
oe = OrdinalEncoder(categories=CATEGORIES)

# Generate encodings
df['Skills Gap'] = oe.fit_transform(df[['Skills Gap']])

In [48]:
df['Professional Network Strength'].unique()

array(['Strong', 'Weak', 'Average'], dtype=object)

In [49]:
# Arrange values according to relative value
CATEGORIES = [['Weak', 'Average', 'Strong']]

# Initialize the OrdinalEncoder
oe = OrdinalEncoder(categories=CATEGORIES)

# Generate encodings
df['Professional Network Strength'] = oe.fit_transform(df[['Professional Network Strength']])

In [50]:
df['Technical Proficiency Level'].unique()

array(['Intermediate', 'Beginner', 'Expert'], dtype=object)

In [51]:
# Arrange values according to relative value
CATEGORIES = [['Beginner', 'Intermediate', 'Expert']]

# Initialize the OrdinalEncoder
oe = OrdinalEncoder(categories=CATEGORIES)

# Generate encodings
df['Technical Proficiency Level'] = oe.fit_transform(df[['Technical Proficiency Level']])

In [52]:
df.sample(10)

,Field of Study,Current Occupation,Age,Gender,Years of Experience,Education Level,Industry Growth Rate,Job Satisfaction Level,Work-Life Balance,# Job Opportunities,Salary,Job Security Level,Interested in Career Change,Skills Gap,Has Mentor,Has Certification,Has Freelancing Experience,Willing to Relocate,Professional Network Strength,# Career Change Events,Technical Proficiency Level,Likely to Change Occupation
7754,Law,Biologist,21.0,Male,39.0,2.0,1.0,1.0,0.0,29.0,32765.0,1.0,No,2.0,N,N,N,No,2.0,1,0.0,Likely
80567,Mechanical Engineering,Mechanical Engineer,58.0,Male,30.0,3.0,1.0,0.0,3.0,37.0,100856.0,1.0,Yes,2.0,N,Y,N,No,1.0,1,0.0,Likely
35730,Psychology,Economist,24.0,Female,16.0,2.0,0.0,1.0,0.0,67.0,37828.0,2.0,No,1.0,N,N,N,Yes,0.0,0,0.0,Likely
74227,Computer Science,Business Analyst,36.0,Male,26.0,2.0,2.0,1.0,0.0,22.0,156682.0,1.0,Yes,2.0,Y,N,N,No,1.0,0,1.0,Likely
53645,Mechanical Engineering,Teacher,38.0,Female,13.0,0.0,2.0,1.0,0.0,73.0,109408.0,1.0,Yes,1.0,N,N,N,Yes,0.0,1,1.0,Likely
17026,Psychology,Teacher,44.0,Female,28.0,0.0,1.0,1.0,0.0,87.0,35766.0,1.0,Yes,0.0,N,N,Y,Yes,0.0,1,0.0,Likely
48732,Mechanical Engineering,Economist,49.0,Female,27.0,2.0,2.0,1.0,3.0,20.0,177228.0,0.0,No,1.0,Y,N,N,No,1.0,2,1.0,Likely
51406,Arts,Biologist,57.0,Female,36.0,0.0,0.0,2.0,0.0,83.0,52570.0,0.0,Yes,0.0,N,N,N,No,0.0,0,1.0,Likely
21408,Biology,Business Analyst,55.0,Female,36.0,2.0,2.0,1.0,0.0,6.0,45072.0,1.0,No,1.0,N,Y,N,No,2.0,1,1.0,Likely
78039,Mechanical Engineering,Software Developer,47.0,Female,35.0,2.0,2.0,2.0,1.0,7.0,142983.0,1.0,Yes,2.0,N,N,N,Yes,1.0,2,0.0,Likely