<a href="https://colab.research.google.com/github/Natalie-Bojorquez/CIS3920Group4/blob/main/CIS3920_Group4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [3920] Career Change Prediction
Data file:
* https://raw.githubusercontent.com/vjavaly/Baruch-CIS-3920/refs/heads/main/data/career_change_prediction_100K.csv

## **EDA Notes**
*   def sample and standard pandas
*   pie chart over count bar graph
*   series.unique
*   lets try a Pearson correlation matrix? in the EDA file
nat to add in bar graphs from CIS 3120
*   important to look for missing values **if so you need to clean it
*   most visualizations to be done in matplotlib/seaborn, skip the pandas bcuz lame
*   most visualizations to be done in matplotlib/seaborn, skip the pandas bcuz lame
*   try using colormap if it works
*   once decide on what visualizations are the best! adjust to side by side for visualizations

In [ ]:
from datetime import datetime
print(f'Run time: {datetime.now().strftime("%D %T")}')

Run time: 10/01/26 15:00:20

In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt     # same as 'import matplotlib.pyplot as plt'
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
### testvtest

In [ ]:
# Read data file
# Field separator is ','
df = pd.read_csv('https://raw.githubusercontent.com/vjavaly/Baruch-CIS-3920/refs/heads/main/data/career_change_prediction_100K.csv',
                 sep=',')

## Viewing Data

In [ ]:
# Display shape of dataframe
df.shape

(100000, 25)

In [ ]:
# Display info about dataframe
df.info()  # 100,000 entries

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Employee ID                    100000 non-null  int64
 1   Employer ID                    100000 non-null  int64
 2   Field of Study                 100000 non-null  object
 3   Current Occupation             100000 non-null  object
 4   Age                            99965 non-null   float64
 5   Gender                         99791 non-null   object
 6   Years of Experience            99514 non-null   float64
 7   Education Level                99696 non-null   object
 8   Industry Growth Rate           99401 non-null   object
 9   Job Satisfaction Level         99528 non-null   object
 10  Work-Life Balance              99603 non-null   object
 11  # Job Opportunities            99610 non-null   float64
 12  Salary                         99653 non-null   float64
 13  Job Security Level             100000 non-null  object
 14  Interested in Career Change    100000 non-null  object
 15  Skills Gap                     100000 non-null  object
 16  Family Influence Level         74640 non-null   object
 17  Has Mentor                     99265 non-null   object
 18  Has Certification              99367 non-null   object
 19  Has Freelancing Experience     100000 non-null  object
 20  Willing to Relocate            100000 non-null  object
 21  Professional Network Strength  100000 non-null  object
 22  # Career Change Events         100000 non-null  int64
 23  Technical Proficiency Level    100000 non-null  object
 24  Likely to Change Occupation    100000 non-null  object
dtypes: float64(4), int64(3), object(18)
memory usage: 19.1+ MB

In [ ]:
# Display column datatypes
df.dtypes

Employee ID                        int64
Employer ID                        int64
Field of Study                    object
Current Occupation                object
Age                              float64
Gender                            object
Years of Experience              float64
Education Level                   object
Industry Growth Rate              object
Job Satisfaction Level            object
Work-Life Balance                 object
# Job Opportunities              float64
Salary                           float64
Job Security Level                object
Interested in Career Change       object
Skills Gap                        object
Family Influence Level            object
Has Mentor                        object
Has Certification                 object
Has Freelancing Experience        object
Willing to Relocate               object
Professional Network Strength     object
# Career Change Events             int64
Technical Proficiency Level       object
Likely to Change Occupation       object
dtype: object

In [ ]:
# Filter for numeric columns
numeric_df = df.select_dtypes(include=[np.number])
numeric_df.columns  # Continuous variables

Index(['Employee ID', 'Employer ID', 'Age', 'Years of Experience',
       '# Job Opportunities', 'Salary', '# Career Change Events'],
      dtype='object')

In [ ]:
# Filter for non-numeric columns
object_df = df.select_dtypes(exclude=[np.number])
object_df.columns # Discrete/Categorical variables

Index(['Field of Study', 'Current Occupation', 'Gender', 'Education Level',
       'Industry Growth Rate', 'Job Satisfaction Level', 'Work-Life Balance',
       'Job Security Level', 'Interested in Career Change', 'Skills Gap',
       'Family Influence Level', 'Has Mentor', 'Has Certification',
       'Has Freelancing Experience', 'Willing to Relocate',
       'Professional Network Strength', 'Technical Proficiency Level',
       'Likely to Change Occupation'],
      dtype='object')

In [ ]:
# Display unique values for non-numerical columns
for col in object_df.columns:         # iterates through each non-numeric column name
  print(f'{col}: {object_df[col].unique()}', end = '\n''\n') # print non-numeric column name with column's unique values. Formatting ending each print statement with a double new line.

Field of Study: ['Biology' 'Economics' 'Medicine' 'Computer Science' 'Psychology'
 'Business' 'Education' 'Law' 'Mechanical Engineering' 'Arts']

Current Occupation: ['Economist' 'Doctor' 'Psychologist' 'Lawyer' 'Biologist' 'Teacher'
 'Artist' 'Business Analyst' 'Software Developer' 'Mechanical Engineer']

Gender: ['Female' 'Male' nan]

Education Level: ["Bachelor's" "Master's" 'PhD' 'High School' nan]

Industry Growth Rate: ['Medium' 'High' 'Low' nan]

Job Satisfaction Level: ['Low' 'Moderate' 'High' nan]

Work-Life Balance: ['Excellent' 'Moderate' 'Poor' 'Good' nan]

Job Security Level: ['Excellent' 'Moderate' 'Poor']

Interested in Career Change: ['No' 'Yes']

Skills Gap: ['High' 'Low' 'Moderate']

Family Influence Level: ['High' 'Low' nan 'Medium']

Has Mentor: ['N' 'Y' nan]

Has Certification: ['N' 'Y' nan]

Has Freelancing Experience: ['N' 'Y']

Willing to Relocate: ['No' 'Yes']

Professional Network Strength: ['Strong' 'Weak' 'Average']

Technical Proficiency Level: ['Intermediate' 'Beginner' 'Expert']

Likely to Change Occupation: ['Likely' 'Unlikely']

In [ ]:
# Replace missing numeric values with an arithmetic (mean or median) strategy
#  Could also have used strategy='median'
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
df['Age'] = imp_mean.fit_transform(df[['Age']])
df['Years of Experience'] = imp_mean.fit_transform(df[['Years of Experience']])
df['Salary'] = imp_mean.fit_transform(df[['Salary']])
df['# Job Opportunities'] = imp_mean.fit_transform(df[['# Job Opportunities']])

In [ ]:
df['Age'].unique()

array([38.        , 44.        , 59.        , 57.        , 36.        ,
       43.        , 34.        , 20.        , 51.        , 55.        ,
       39.        , 45.        , 42.        , 21.        , 49.        ,
       32.        , 48.        , 23.        , 53.        , 47.        ,
       58.        , 56.        , 35.        , 25.        , 37.        ,
       27.        , 30.        , 31.        , 50.        , 54.        ,
       52.        , 46.        , 41.        , 24.        , 33.        ,
       40.        , 29.        , 26.        , 22.        , 28.        ,
       39.60266093])

In [ ]:
# Replace missing non-numeric values with a most_frequent (mode) strategy
imp_most_freq = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
df['Gender'] = imp_most_freq.fit_transform(df[['Gender']]).ravel()
df['Education Level'] = imp_most_freq.fit_transform(df[['Education Level']]).ravel()
df['Job Satisfaction Level'] = imp_most_freq.fit_transform(df[['Job Satisfaction Level']]).ravel()
df['Has Mentor'] = imp_most_freq.fit_transform(df[['Has Mentor']]).ravel()
df['Has Certification'] = imp_most_freq.fit_transform(df[['Has Certification']]).ravel()
df['Industry Growth Rate'] = imp_most_freq.fit_transform(df[['Industry Growth Rate']]).ravel()
df['Work-Life Balance'] = imp_most_freq.fit_transform(df[['Work-Life Balance']]).ravel()

In [ ]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [ ]:
# Check for missing values
df.isnull().sum()

Employee ID                          0
Employer ID                          0
Field of Study                       0
Current Occupation                   0
Age                                  0
Gender                               0
Years of Experience                  0
Education Level                      0
Industry Growth Rate                 0
Job Satisfaction Level               0
Work-Life Balance                    0
# Job Opportunities                  0
Salary                               0
Job Security Level                   0
Interested in Career Change          0
Skills Gap                           0
Family Influence Level           25360
Has Mentor                           0
Has Certification                    0
Has Freelancing Experience           0
Willing to Relocate                  0
Professional Network Strength        0
# Career Change Events               0
Technical Proficiency Level          0
Likely to Change Occupation          0
dtype: int64

In [ ]:
# Differentiate Ordinal and Nominal valued categorical columns

In [ ]:
# Display the # of unique values for column Employee_ID
df['Employee ID'].nunique() # check to see column's number of unique values
                           # 99,747 != 100,000 rows ... duplicate values

99747

In [ ]:
# Check to see if duplicate Employee IDs have different Employer IDs

In [ ]:
# Count amount of duplicated rows
df.duplicated().sum()

np.int64(253)

In [ ]:
# Display duplicated rows
df[df.duplicated(keep=False)]

 #too many columns? maybe we go back a step to analyze it better

,Employee ID,Employer ID,Field of Study,Current Occupation,Age,Gender,Years of Experience,Education Level,Industry Growth Rate,Job Satisfaction Level,...,Skills Gap,Family Influence Level,Has Mentor,Has Certification,Has Freelancing Experience,Willing to Relocate,Professional Network Strength,# Career Change Events,Technical Proficiency Level,Likely to Change Occupation
345,522690,87326,Business,Lawyer,57.0,Female,13.0,PhD,High,Moderate,...,Low,Low,N,Y,N,Yes,Weak,2,Intermediate,Likely
538,556524,13309,Medicine,Doctor,47.0,Female,18.0,Master's,Medium,High,...,High,NaN,N,N,Y,No,Weak,2,Beginner,Likely
645,815136,87326,Arts,Lawyer,58.0,Female,31.0,Master's,High,Low,...,Moderate,Low,N,N,Y,Yes,Weak,0,Intermediate,Likely
767,484591,50154,Arts,Doctor,25.0,Female,8.0,High School,Medium,Moderate,...,Low,High,N,Y,N,Yes,Average,1,Intermediate,Likely
824,818702,38672,Law,Software Developer,25.0,Male,21.0,High School,Medium,Moderate,...,Moderate,High,N,N,N,No,Weak,1,Intermediate,Likely
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99006,377293,13309,Arts,Psychologist,36.0,Male,35.0,High School,Medium,Low,...,Low,NaN,N,N,N,No,Strong,1,Intermediate,Likely
99052,119156,53209,Psychology,Lawyer,53.0,Female,10.0,PhD,High,High,...,High,Low,N,Y,N,No,Strong,1,Expert,Likely
99165,775633,42741,Business,Business Analyst,43.0,Female,15.0,Bachelor's,High,Moderate,...,Moderate,Medium,N,N,N,No,Average,2,Expert,Unlikely
99356,241236,60225,Education,Biologist,23.0,Male,34.0,Master's,Low,Low,...,High,High,N,N,Y,No,Average,1,Beginner,Likely
99636,710402,22363,Business,Psychologist,36.0,Male,18.0,Master's,Low,Low,...,Low,High,N,N,N,Yes,Average,0,Intermediate,Likely

## Cleaning Data

In [ ]:
# Remove duplicate rows based on all columns keeping only the first occurrence of each unique row
df.drop_duplicates(inplace=True) # inplace = True to modify original dataframe

In [ ]:
# Confirm removed duplicated rows
df.duplicated().sum()

np.int64(0)

In [ ]:
# Display updated dataframe shape
df.shape

(99747, 25)

In [ ]:
# Display updated dataframe info
# Potentially drop these columns free lance experience, willing to relocate
# Maybe drop Employer IF
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99747 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Employee ID                    99747 non-null  int64
 1   Employer ID                    99747 non-null  int64
 2   Field of Study                 99747 non-null  object
 3   Current Occupation             99747 non-null  object
 4   Age                            99713 non-null  float64
 5   Gender                         99542 non-null  object
 6   Years of Experience            99263 non-null  float64
 7   Education Level                99444 non-null  object
 8   Industry Growth Rate           99149 non-null  object
 9   Job Satisfaction Level         99276 non-null  object
 10  Work-Life Balance              99350 non-null  object
 11  # Job Opportunities            99357 non-null  float64
 12  Salary                         99402 non-null  float64
 13  Job Security Level             99747 non-null  object
 14  Interested in Career Change    99747 non-null  object
 15  Skills Gap                     99747 non-null  object
 16  Family Influence Level         74454 non-null  object
 17  Has Mentor                     99017 non-null  object
 18  Has Certification              99114 non-null  object
 19  Has Freelancing Experience     99747 non-null  object
 20  Willing to Relocate            99747 non-null  object
 21  Professional Network Strength  99747 non-null  object
 22  # Career Change Events         99747 non-null  int64
 23  Technical Proficiency Level    99747 non-null  object
 24  Likely to Change Occupation    99747 non-null  object
dtypes: float64(4), int64(3), object(18)
memory usage: 19.8+ MB

In [ ]:
# Comfirm all unique values for Employee ID
df['Employee ID'].nunique() # 99,747 == 99,747,000 rows

99747

In [ ]:
# Make column Employee ID the index column
df.set_index('Employee ID', inplace=True)
df.head() # show first 5

,Employer ID,Field of Study,Current Occupation,Age,Gender,Years of Experience,Education Level,Industry Growth Rate,Job Satisfaction Level,Work-Life Balance,...,Skills Gap,Family Influence Level,Has Mentor,Has Certification,Has Freelancing Experience,Willing to Relocate,Professional Network Strength,# Career Change Events,Technical Proficiency Level,Likely to Change Occupation
Employee ID,,,,,,,,,,,,,,,,,,,,,
574511,38672,Biology,Economist,38.0,Female,7.0,Bachelor's,Medium,Low,Excellent,...,High,High,N,N,N,No,Strong,1,Intermediate,Likely
447956,22363,Economics,Doctor,44.0,Female,0.0,Master's,Medium,Moderate,Moderate,...,Low,Low,N,Y,N,No,Weak,1,Beginner,Likely
757898,42741,Medicine,Doctor,59.0,Male,10.0,PhD,Medium,Low,Poor,...,Low,NaN,N,Y,N,No,Average,2,Beginner,Likely
583528,92445,Medicine,Psychologist,57.0,Female,14.0,High School,Medium,Low,Poor,...,Moderate,Medium,N,N,N,No,Average,1,Expert,Likely
466234,39433,Computer Science,Lawyer,36.0,Female,23.0,PhD,High,Low,Excellent,...,High,Low,N,N,N,Yes,Weak,0,Intermediate,Likely

In [ ]:
# Display statistical summary of numeric columns
df.describe() # NOT YET accounted for null values

,Employer ID,Age,Years of Experience,# Job Opportunities,Salary,# Career Change Events
count,99747.000000,99713.000000,99263.000000,99357.000000,99402.000000,99747.000000
mean,53543.333444,39.602399,19.485548,50.287005,109017.152753,1.008923
std,24529.951430,11.623597,11.517518,28.874180,51212.112865,0.814793
min,13309.000000,20.000000,0.000000,1.000000,30005.000000,0.000000
25%,38672.000000,30.000000,10.000000,25.000000,61744.000000,0.000000
50%,53209.000000,40.000000,20.000000,50.000000,107696.000000,1.000000
75%,75617.000000,50.000000,29.000000,75.000000,153383.250000,2.000000
max,92445.000000,59.000000,39.000000,100.000000,199996.000000,2.000000

In [ ]:
# Display statistics for non-numerical data
object_df.describe() # NOT YET accounted for null values

,Field of Study,Current Occupation,Gender,Education Level,Industry Growth Rate,Job Satisfaction Level,Work-Life Balance,Job Security Level,Interested in Career Change,Skills Gap,Family Influence Level,Has Mentor,Has Certification,Has Freelancing Experience,Willing to Relocate,Professional Network Strength,Technical Proficiency Level,Likely to Change Occupation
count,100000,100000,99791,99696,99401,99528,99603,100000,100000,100000,74640,99265,99367,100000,100000,100000,100000,100000
unique,10,10,2,4,3,3,4,3,2,3,3,2,2,2,2,3,3,2
top,Business,Artist,Female,Master's,Medium,Low,Poor,Poor,No,Moderate,High,N,N,N,No,Average,Intermediate,Likely
freq,10371,10226,49914,25219,33485,47392,39575,40215,68012,40405,25315,69632,69560,85252,69277,40901,50228,91784